---
title: "Simulation + Inference: 20 runs"
output: rmarkdown::html_document
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4, tibble.print_max = 4)
```

```{r}
set.seed(3)
library(ggplot2)
library(reshape2)
library(viridis)
library(ResistPhy)
library(ape)
library(posterior)
library(cmdstanr)
library(bayesplot)
library(phylodyn)
library(latex2exp)
```

## Simulation function 
```{r}
source("simu_phylo.R")
```
## Generate recovery parameter set
```{r, out.width="100%", dpi=300, fig.align="center"}
usage_df <- simulated_usage()

n_runs <- 50

run_idx <- c(1:n_runs)
usage_df <- simulated_usage()

set.seed(123456)
traj_seeds <- sample.int(n=100000, n_runs, F)
set.seed(457869)
phy_seeds <- sample.int(n=100000, n_runs, F)

q_u <- seq(from=1.0, to=1.2, length.out=n_runs)
q_t <- seq(from=1.0, to=0.5, length.out=n_runs)

t0 <- min(usage_df$time)
tmax <- max(usage_df$time)
gamma_sus <- 1/60.0*365.0
n_tip <- 200

gamma_u <- gamma_sus*q_u
gamma_t <- gamma_sus*q_t

para_df <- data.frame(gamma_u=gamma_u, gamma_t=gamma_t, idx = c(1:n_runs))
ggplot(melt(para_df, "idx", variable.name="parameter")) + 
    geom_point(aes(x=idx, y=value, shape=parameter, color=parameter)) +
    geom_hline(yintercept=gamma_sus) + 
    theme_bw()

facet_labs <- sapply(c(1:n_runs), function(i) TeX(sprintf("$q_{u}$: %.3f $q_{t}$: %.3f", q_u[i], q_t[i])))

phys <- list()
most_recent_samp <- list()
traj_df <- data.frame(t=c(), y=c(), strain=c(), para_idx=c())
Ne_df <- data.frame(t=c(), y=c(), strain=c(), para_idx=c())

for (i in c(1:n_runs)) {
    idx <- run_idx[i]
    sim_out <- sample_phylo(gamma_sus, gamma_u[idx], gamma_t[idx], n_tip, traj_seeds[idx], phy_seeds[idx])
    sim_df <- sim_out$traj
    n <- nrow(sim_df)
    sub_idx <- seq.int(from=1, to=n, length.out=1e3)
    sim_df <- sim_df[sub_idx,]
    sim_df$Ne_s <- sim_df$I_2/2/sim_df$inf_rate 
    sim_df$Ne_r <- sim_df$I_3/2/sim_df$inf_rate 
    
    append_df <- melt(sim_df[,c("t","I_2","I_3")], "t", variable.name="strain", value.name="y") 
    append_ne_df <- melt(sim_df[,c("t","Ne_s","Ne_r")], "t", variable.name="strain", value.name="y") 

    append_df$para_idx <- i
    append_ne_df$para_idx <- i
    traj_df <- rbind(traj_df, append_df)
    Ne_df <- rbind(Ne_df, append_ne_df)

    phys[[i]] <- sim_out$phys
    most_recent_samp[[i]] <- sim_out$most_recent_samp
}

traj_df$para_idx <- factor(traj_df$para_idx, levels=c(1:n_runs), labels=facet_labs)

tplt <- ggplot(traj_df) + 
    geom_line(aes(x=t, y=y, color=strain)) + 
    scale_color_manual(values = c(I_3 = "red", I_2 = "blue"), labels=c("Resistant", "Susceptible")) + 
    facet_wrap(~para_idx, nrow=10, labeller=label_parsed) +
    labs(x="Time", y="Population Size") +
    theme_bw()
tplt
pdf("Figures/sims_large_200.pdf",16,16)
tplt
dev.off()
```

# Read Results

```{r, eval=T}
par_files <- list.files(pattern="det_para.*\\.rds")
conv_files <- list.files(pattern="det_conv.*\\.rds")

recovery_data <- do.call(rbind, lapply(par_files, readRDS))
conv_data <- do.call(c, lapply(conv_files, readRDS))
```

```{r, eval=T}
print(conv_data)
```

# Plot
```{r, out.width="100%", dpi=300, fig.align="center", eval=T}
gt_df <- melt(data.frame(q_u=q_u, q_t=q_t, para_idx = c(1:n_runs)), measure.vars=c("q_u", "q_t"), 
                variable.name="variable", value.name="value")
iplt <- ggplot(recovery_data) + 
    geom_pointrange(mapping = aes(x = para_idx, y = value, color=variable, group=variable),
                  stat = "summary",
                  fun.min = function(z) {quantile(z,0.025)},
                  fun.max = function(z) {quantile(z,0.975)},
                  fun = median) +
    geom_line(data=gt_df, aes(x=para_idx, y = value, color=variable, group=variable), linetype="longdash") +
    labs(x="Simulation", y="Value", color="Variable") +
    scale_colour_manual(
        values = c("lightsteelblue4", "lightsteelblue1"),
        breaks = c("q_t", "q_u"),
        labels = c(TeX("$\\q_t$"), TeX("$\\q_u$"))) +
    theme_minimal() +
    theme(axis.text.x=element_text(size=rel(1.5)),
        axis.text.y=element_text(size=rel(1.5)),
        aspect.ratio=1,
        plot.margin = margin(0.2, 0.2, 0.2, 0.2, "cm"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(size=rel(0.2), colour = "grey90"),
        plot.title = element_text(hjust = 0.5,size=rel(1.0)))

iplt

pdf("Figures/recovery_large200.pdf", 6,6)
iplt
dev.off()
```
